# Schema for the configuration files of the XMLSitemap module.

xmlsitemap.settings:
    type: mapping
    label: 'XMLSitemap settings'
    mapping:
        rebuild_needed:
            type: boolean
            label: 'Sitemap rebuilt'
        regenerate_needed: 
            type: boolean
            label: 'Regenerate files'
        minimum_lifetime:
            type: integer
            label: 'Minumum lifetime of an xmlsitemap xml file'
        generated_last:
            type: integer
            label: 'Last generated sitemap'
        xsl:
            type: integer
            label: 'Check XSL functionality'
        prefetch_aliases:
            type: integer
            label: 'Decide to prefetch aliases'
        chunk_size:
            type: string
            label: 'Set chunk size'
        batch_limit:
            type: integer
            label: 'Set batch limit'
        path:
            type: string
            label: 'Path of the XML generated files'
        frontpage_priority:
            type: float
            label: 'Priority of the frontpage'
        frontpage_changefreq:
            type: integer
            label: 'Change frequency for frontpage'
        lastmod_format:
            type: integer
            label: 'Last modified xmlsitemap format'
        gz:
            type: boolean
            label: 'Gz'
        clean_url:
            type: integer
            label: 'Insert clean urls into sitemap'
        cron_threshold_error:
            type: integer
            label: 'Threshold error for cron job'
        cron_threshold_warning:
            type: integer
            label: 'Threshold warning for cron job'
        regenerate_last:
            type: undefined
            label: 'Last regenerate xmlsitemap'
        custom_links:
            type: undefined
            label: 'Custom links'
        priority_default:
            type: undefined
            label: 'Default priority for a link'
        languages:
            type: mapping
            label: 'Languages for xmlsitemap'
        max_chunks:
            type: undefined
            label: 'Max chunks'
        max_filesize:
            type: undefined
            label: 'Maximul size of xml file'

