# Schema for the configuration files of the XMLSitemap module.

xmlsitemap.settings:
    type: mapping
    label: 'XMLSitemap settings'
    mapping:
        xmlsitemap_rebuild_needed:
            type: boolean
            label: 'Sitemap rebuilt'
        xmlsitemap_regenerate_needed: 
            type: boolean
            label: 'Regenerate files'
        xmlsitemap_minimum_lifetime:
            type: integer
            label: 'Minumum lifetime of an xmlsitemap xml file'
        xmlsitemap_generated_last:
            type: integer
            label: 'Last generated sitemap'
        xmlsitemap_xsl:
            type: integer
            label: 'Check XSL functionality'
        xmlsitemap_prefetch_aliases:
            type: integer
            label: 'Decide to prefetch aliases'
        xmlsitemap_chunk_size:
            type: string
            label: 'Set chunk size'
        xmlsitemap_batch_limit:
            type: integer
            label: 'Set batch limit'
        xmlsitemap_path:
            type: string
            label: 'Path of the XML generated files'
        xmlsitemap_base_url:
            type: string
            label: 'URL for XML sitemap file'
        xmlsitemap_developer_mode:
            type: integer
            label: 'Check if is developer mode'
        xmlsitemap_frontpage_priority:
            type: float
            label: 'Priority of the frontpage'
        xmlsitemap_frontpage_changefreq:
            type: integer
            label: 'Change frequency for frontpage'
        xmlsitemap_lastmod_format:
            type: integer
            label: 'Last modified xmlsitemap format'
        xmlsitemap_gz:
            type: boolean
            label: 'Gz'
        clean_url:
            type: integer
            label: 'Insert clean urls into sitemap'
        cron_threshold_error:
            type: integer
            label: 'Threshold error for cron job'
        cron_threshold_warning:
            type: integer
            label: 'Threshold warning for cron job'
        xmlsitemap_regenerate_last:
            type: undefined
            label: 'Last regenerate xmlsitemap'
        xmlsitemap_custom_links:
            type: undefined
            label: 'Custom links'
        xmlsitemap_priority_default:
            type: undefined
            label: 'Default priority for a link'
        xmlsitemap_languages:
            type: mapping
            label: 'Languages for xmlsitemap'
        xmlsitemap_max_chunks:
            type: undefined
            label: 'Max chunks'
        xmlsitemap_max_filesize:
            type: undefined
            label: 'Maximul size of xml file'

